### ISSUE TITLE
Header y Navbar

### ISSUE THREAD

**Issue by alexfuser** [CodeandoMexico/codeandomexico#1]
Realizar la estructura del Header y Navbar 

Los recursos gráficos están por enviarlos.

![imagen](https://user-images.githubusercontent.com/1179211/43201383-f3c210f0-8fdd-11e8-9480-7fa511064b59.png)

**Comment by flkt-crnpio** [comment]
Hay una actualización de esta sección en <dev branch ... esperando por el gráfico

**Comment by flkt-crnpio** [comment]
terminé el smooth scroll en la navegación general de la página, deje el header fijo arriba y agregué las ligas de los enlaces externos. todo esta en dev branch
