### ISSUE TITLE
Sobre anchura de la sección de inicio

### ISSUE THREAD

**Issue by mendozagioo** [CodeandoMexico/codeandomexico#19]
Ya que se usa la unidad de anchura de viewport en la sección de inicio, se sobrepasa la anchura del 100% de todo la página y genera un pequeño scroll horizontal.
![vertical_scroll](https://user-images.githubusercontent.com/1576290/44937829-e4075c80-ad40-11e8-9fb8-4d3b2aeeb849.png)

**Comment by alexfuser** [comment]
@mendozagioo me podrías indicar con que navegador hiciste pruebas? no me sale ningún scroll en x

**Comment by mendozagioo** [comment]
Lo veo en:
- Chrome Versión 68.0.3440.106
- Firefox Versión 61.0.2
- Safari Versión 11.1.2

**Comment by alexfuser** [comment]
@mendozagioo 

Ya veo. A mi no me sale el scroll en x sobre las mismas versiones de navegador.

Veo que tu resolución es un poco mayor a la que tengo. Es una Imac? la mía un mac de 15 pulgadas.


<img width="1440" alt="captura de pantalla 2018-09-03 a la s 11 09 20" src="https://user-images.githubusercontent.com/1179211/44995685-db459f00-af69-11e8-8f82-338df8570450.png">


Si te das cuenta no cuento con scroll en x. No tienes el porcentaje de tu ventana mayor de 100% ?

**Comment by mendozagioo** [comment]
No, no tengo mi porcentaje mayor, además al aumentar el porcentaje a mas del 100% la web debe comportarse sin cambios, el problema no es es ese, el problema es el el uso del vw como lo dije al principio. Yo sólo quiero ayudar a que la web se vea sin scroll horizontal, sin importar en que pantalla se esté viendo y sin importar la resolución.

**Comment by flkt-crnpio** [comment]
ya pude replicarlo en windows!  @mendozagioo gracias por reportar. @alexfuser ahorita subo el fix a dev

**Comment by mendozagioo** [comment]
oye @flkt-crnpio si viste que envié mi PR? osea, no sólo reporte, sino que envié mi solución!

**Comment by flkt-crnpio** [comment]
oh, lo siento, no lo vi @mendozagioo . lo revisé porque me avisaron por mensaje que le echara un ojo, hasta ahorita entré nada mas para avisarles que ya estaba en eso.

**Comment by almarngl** [comment]
Sí, ya está el PR, es sólo cuestión de darle review y merge @flkt-crnpio :)

**Comment by flkt-crnpio** [comment]
listo @mendozagioo gracias por ayudar! ya está tu solución en dev
