### ISSUE TITLE
Sección Proyectos

### ISSUE THREAD

**Issue by alexfuser** [CodeandoMexico/codeandomexico#2]
Realizar la estructura de la sección de proyectos.

![imagen](https://user-images.githubusercontent.com/1179211/43201519-58a605c6-8fde-11e8-8461-8feccca05cbd.png)

**Comment by flkt-crnpio** [comment]
Necesitamos descripción de cada proyecto, un link a donde mandar con la acción de <visitar> y también a donde mandar o qué pasa cuando das click en <cuéntanos tu proyecto>

**Comment by jorandradefig** [comment]
¿Entonces esta sección ya quedó?

**Comment by flkt-crnpio** [comment]
no, no hay contenido aun

**Comment by almarngl** [comment]
@flkt-crnpio Listo, [acá](https://docs.google.com/document/d/1fS0TE1S5Goo3ZiilKGkOcwdA8Qdiuc8hcuVYg7pX9jo/edit?usp=sharing ) esta el contenido del sitio, incluyendo los proyectos. 

Sólo me queda una duda, ¿de qué tamaño se necesitan las imágenes de cada cuadrito?

**Comment by flkt-crnpio** [comment]
@almarngl  creo que de 500x350px se ve bien en todas las resoluciones

**Comment by alexfuser** [comment]
![aulascmx](https://user-images.githubusercontent.com/1179211/44623915-0150ac80-a8a3-11e8-80af-68683787181b.png)
![datamx](https://user-images.githubusercontent.com/1179211/44623916-0150ac80-a8a3-11e8-9abd-192a7c0cc8ec.png)
![drtoolkit](https://user-images.githubusercontent.com/1179211/44623917-01e94300-a8a3-11e8-8f3b-c498fd42824b.png)
![estudiantes](https://user-images.githubusercontent.com/1179211/44623918-01e94300-a8a3-11e8-80db-0f438909edb4.png)
![hermosilloabierto](https://user-images.githubusercontent.com/1179211/44623919-01e94300-a8a3-11e8-96cb-066839f479bd.png)
![informebajolupa](https://user-images.githubusercontent.com/1179211/44623920-01e94300-a8a3-11e8-9b53-0a03bd3173e7.png)
![mapaton](https://user-images.githubusercontent.com/1179211/44623921-01e94300-a8a3-11e8-8f5a-4bebbf58ef73.png)
![retos](https://user-images.githubusercontent.com/1179211/44623922-01e94300-a8a3-11e8-8dce-5337812bd0f9.png)
![sismomx](https://user-images.githubusercontent.com/1179211/44623923-0281d980-a8a3-11e8-8525-9ea466b9ff6b.png)

**Comment by flkt-crnpio** [comment]
:} grashiash @alexfuser por las imagenes
