### ISSUE TITLE
Copy Colabora ONGs

### ISSUE THREAD

**Issue by almarngl** [CodeandoMexico/codeandomexico#24]
Cambiar el copy por: 

"Podemos colaborar o crear proyectos en conjunto que:

< Desarrollen capacidades técnicas dentro de tu organización />
< Aumenten el impacto de tu trabajo  /> 
< Identifiquen problemas públicos y posibles soluciones tecnológicas />
< Abran procesos y datos para colaborar con tecnólogos />
< Nos permitan encontrar respuestas a sus retos en conjunto />
< ¡Otras ideas que se te ocurran! />"

**Comment by alexfuser** [comment]
Listo
