### ISSUE TITLE
Sección Colabora con nosotros

### ISSUE THREAD

**Issue by alexfuser** [CodeandoMexico/codeandomexico#4]
Realizar la estructura de la sección colabora con nosotros

![imagen](https://user-images.githubusercontent.com/1179211/43201769-09dcf8c2-8fdf-11e8-9877-ec4d77e97e12.png)

**Comment by flkt-crnpio** [comment]
esta sección tiene el diseño final @alexfuser ?

**Comment by alexfuser** [comment]
así es @flkt-crnpio

**Comment by flkt-crnpio** [comment]
me faltan las imágenes, las intenté dibujar en css, pero creo que sería más fácil si me pueden mandar pngs o svgs . los cambios están en el branch dev @alexfuser

**Comment by flkt-crnpio** [comment]
imágenes y tipografías actualizadas en dev! gracias  @alexfuser
