### ISSUE TITLE
Newsletter y Footer

### ISSUE THREAD

**Issue by alexfuser** [CodeandoMexico/codeandomexico#5]
Realizar la estructura del Newsletter y Footer

![imagen](https://user-images.githubusercontent.com/1179211/43201857-527ce47a-8fdf-11e8-9c6d-546602f1418c.png)

**Comment by flkt-crnpio** [comment]
la sección de news letter a donde conecta? y los links del footer como 'proyectos abiertos' 'participa' etc... también estaría bueno definir a donde van

**Comment by almarngl** [comment]
@flkt-crnpio la sección de newsletter conecta a nuestra cuenta de Mailchimp. De "Proyectos abiertos" y "Participa" van justo a cada una de esas secciones del sitio.

**Comment by flkt-crnpio** [comment]
:} listo en dev branch
